cleanup

diff --git a/bin/travisci b/bin/travisci
--- a/bin/travisci
+++ b/bin/travisci
@@ -5,10 +5,21 @@ set -xe
 # Publish local dependencies when not in a master branch
 SCROOGE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
+function cleanup {
+  rm -rf $SCROOGE_TMP_DIR
+  echo Removed $SCROOGE_TMP_DIR
+}
+# Cleanup when done or interrupted
+trap cleanup SIGHUP SIGINT SIGTERM EXIT
+
 if [ "$SCROOGE_BRANCH" != "master" ]; then
   SCROOGE_DIR=$(pwd)
    # TODO try to use ./sbt of each project instead of scrooge's sbt
   SCROOGE_SBT=$SCROOGE_DIR/sbt
+
+  # Set when running locally
+  TRAVIS_SCALA_VERSION=${TRAVIS_SCALA_VERSION:-2.10.5}
+
   SCROOGE_TMP_DIR=$(mktemp -d -t scrooge.XXXXXXXXXX.tmp)
   # util
   cd $SCROOGE_TMP_DIR
@@ -33,7 +44,4 @@ if [ "$SCROOGE_BRANCH" != "master" ]; then
   $SCROOGE_SBT ++$TRAVIS_SCALA_VERSION finagle-thrift/publishLocal
   $SCROOGE_SBT ++$TRAVIS_SCALA_VERSION finagle-thriftmux/publishLocal
   $SCROOGE_SBT ++$TRAVIS_SCALA_VERSION finagle-ostrich4/publishLocal
-  # clean up
-  cd $SCROOGE_DIR
-  rm -rf $SCROOGE_TMP_DIR
 fi
